# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Main Test & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Python Virtual Environment
        run : python -m venv python3-virtualenv

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ] 
          then 
            pip install -r requirements.txt
          fi
          
      - name: Test with unittest
        run: ./run-test.sh
        
      - name: Send Testing Failure Message
        if: failure()
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Testing Failed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh -i $SSH_KEY_PATH root@${{secrets.SSH_HOSTNAME}} './redeploy-site.sh'
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          
      - name: Run Deploy Script
        run: ssh -i $SSH_KEY_PATH root@${{secrets.SSH_HOSTNAME}} './redeploy-site.sh'
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      
      - name: Check Status
        run: ssh -i $SSH_KEY_PATH root@${{secrets.SSH_HOSTNAME}} 'cd portfolio; docker compose -f docker-compose.prod.yml ps'
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          
      - name: Send Deployment Success Message
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successfu! embeds=https://nico-ruiz.duckdns.org/"
          
      - name: Send Deployment Failure Message
        if: failure()
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed"
